CI: Trying to force a build failure

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -84,6 +84,8 @@ jobs:
         run: |
           mkdir build
           cd build
+          echo "Forcing a failure for test purposes"
+          exit 1
           make -f ../Makefile config-$CC
           make -f ../Makefile -j$procs
           make -f ../Makefile unit-test -j$procs
